export default {
  data: {
    id: 66407038,
    name: 'tds',
    full_name: 'telusdigital/tds',
    owner: {
      login: 'telusdigital',
      id: 9374493,
      avatar_url: 'https://avatars1.githubusercontent.com/u/9374493?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/telusdigital',
      html_url: 'https://github.com/telusdigital',
      followers_url: 'https://api.github.com/users/telusdigital/followers',
      following_url: 'https://api.github.com/users/telusdigital/following{/other_user}',
      gists_url: 'https://api.github.com/users/telusdigital/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/telusdigital/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/telusdigital/subscriptions',
      organizations_url: 'https://api.github.com/users/telusdigital/orgs',
      repos_url: 'https://api.github.com/users/telusdigital/repos',
      events_url: 'https://api.github.com/users/telusdigital/events{/privacy}',
      received_events_url: 'https://api.github.com/users/telusdigital/received_events',
      type: 'Organization',
      site_admin: false,
    },
    private: false,
    html_url: 'https://github.com/telusdigital/tds',
    description: 'TELUS Design System',
    fork: false,
    url: 'https://api.github.com/repos/telusdigital/tds',
    forks_url: 'https://api.github.com/repos/telusdigital/tds/forks',
    keys_url: 'https://api.github.com/repos/telusdigital/tds/keys{/key_id}',
    collaborators_url: 'https://api.github.com/repos/telusdigital/tds/collaborators{/collaborator}',
    teams_url: 'https://api.github.com/repos/telusdigital/tds/teams',
    hooks_url: 'https://api.github.com/repos/telusdigital/tds/hooks',
    issue_events_url: 'https://api.github.com/repos/telusdigital/tds/issues/events{/number}',
    events_url: 'https://api.github.com/repos/telusdigital/tds/events',
    assignees_url: 'https://api.github.com/repos/telusdigital/tds/assignees{/user}',
    branches_url: 'https://api.github.com/repos/telusdigital/tds/branches{/branch}',
    tags_url: 'https://api.github.com/repos/telusdigital/tds/tags',
    blobs_url: 'https://api.github.com/repos/telusdigital/tds/git/blobs{/sha}',
    git_tags_url: 'https://api.github.com/repos/telusdigital/tds/git/tags{/sha}',
    git_refs_url: 'https://api.github.com/repos/telusdigital/tds/git/refs{/sha}',
    trees_url: 'https://api.github.com/repos/telusdigital/tds/git/trees{/sha}',
    statuses_url: 'https://api.github.com/repos/telusdigital/tds/statuses/{sha}',
    languages_url: 'https://api.github.com/repos/telusdigital/tds/languages',
    stargazers_url: 'https://api.github.com/repos/telusdigital/tds/stargazers',
    contributors_url: 'https://api.github.com/repos/telusdigital/tds/contributors',
    subscribers_url: 'https://api.github.com/repos/telusdigital/tds/subscribers',
    subscription_url: 'https://api.github.com/repos/telusdigital/tds/subscription',
    commits_url: 'https://api.github.com/repos/telusdigital/tds/commits{/sha}',
    git_commits_url: 'https://api.github.com/repos/telusdigital/tds/git/commits{/sha}',
    comments_url: 'https://api.github.com/repos/telusdigital/tds/comments{/number}',
    issue_comment_url: 'https://api.github.com/repos/telusdigital/tds/issues/comments{/number}',
    contents_url: 'https://api.github.com/repos/telusdigital/tds/contents/{+path}',
    compare_url: 'https://api.github.com/repos/telusdigital/tds/compare/{base}...{head}',
    merges_url: 'https://api.github.com/repos/telusdigital/tds/merges',
    archive_url: 'https://api.github.com/repos/telusdigital/tds/{archive_format}{/ref}',
    downloads_url: 'https://api.github.com/repos/telusdigital/tds/downloads',
    issues_url: 'https://api.github.com/repos/telusdigital/tds/issues{/number}',
    pulls_url: 'https://api.github.com/repos/telusdigital/tds/pulls{/number}',
    milestones_url: 'https://api.github.com/repos/telusdigital/tds/milestones{/number}',
    notifications_url:
      'https://api.github.com/repos/telusdigital/tds/notifications{?since,all,participating}',
    labels_url: 'https://api.github.com/repos/telusdigital/tds/labels{/name}',
    releases_url: 'https://api.github.com/repos/telusdigital/tds/releases{/id}',
    deployments_url: 'https://api.github.com/repos/telusdigital/tds/deployments',
    created_at: '2016-08-23T22:07:13Z',
    updated_at: '2018-04-09T15:33:29Z',
    pushed_at: '2018-04-09T20:44:48Z',
    git_url: 'git://github.com/telusdigital/tds.git',
    ssh_url: 'git@github.com:telusdigital/tds.git',
    clone_url: 'https://github.com/telusdigital/tds.git',
    svn_url: 'https://github.com/telusdigital/tds',
    homepage: 'https://tds.telus.com',
    size: 93886,
    stargazers_count: 20,
    watchers_count: 20,
    language: 'JavaScript',
    has_issues: true,
    has_projects: false,
    has_downloads: true,
    has_wiki: false,
    has_pages: false,
    forks_count: 4,
    mirror_url: null,
    archived: false,
    open_issues_count: 28,
    license: {
      key: 'mit',
      name: 'MIT License',
      spdx_id: 'MIT',
      url: 'https://api.github.com/licenses/mit',
    },
    forks: 4,
    open_issues: 28,
    watchers: 20,
    default_branch: 'master',
    permissions: { admin: true, push: true, pull: true },
    allow_squash_merge: true,
    allow_merge_commit: false,
    allow_rebase_merge: true,
    organization: {
      login: 'telusdigital',
      id: 9374493,
      avatar_url: 'https://avatars1.githubusercontent.com/u/9374493?v=4',
      gravatar_id: '',
      url: 'https://api.github.com/users/telusdigital',
      html_url: 'https://github.com/telusdigital',
      followers_url: 'https://api.github.com/users/telusdigital/followers',
      following_url: 'https://api.github.com/users/telusdigital/following{/other_user}',
      gists_url: 'https://api.github.com/users/telusdigital/gists{/gist_id}',
      starred_url: 'https://api.github.com/users/telusdigital/starred{/owner}{/repo}',
      subscriptions_url: 'https://api.github.com/users/telusdigital/subscriptions',
      organizations_url: 'https://api.github.com/users/telusdigital/orgs',
      repos_url: 'https://api.github.com/users/telusdigital/repos',
      events_url: 'https://api.github.com/users/telusdigital/events{/privacy}',
      received_events_url: 'https://api.github.com/users/telusdigital/received_events',
      type: 'Organization',
      site_admin: false,
    },
    network_count: 4,
    subscribers_count: 28,
  },
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers':
      'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
    'cache-control': 'private, max-age=60, s-maxage=60',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Mon, 09 Apr 2018 21:23:40 GMT',
    etag: 'W/"fef8dd2525733b46b7e3cfb50f56600c"',
    'last-modified': 'Mon, 09 Apr 2018 15:33:29 GMT',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '200 OK',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    vary: 'Accept, Authorization, Cookie, X-GitHub-OTP',
    'x-accepted-oauth-scopes': 'repo',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; param=drax-preview; format=json',
    'x-github-request-id': 'CD9F:687F:14FE896:2F81ACA:5ACBD9DC',
    'x-oauth-scopes': 'read:org, repo',
    'x-ratelimit-limit': '5000',
    'x-ratelimit-remaining': '4866',
    'x-ratelimit-reset': '1523309344',
    'x-runtime-rack': '0.070992',
    'x-xss-protection': '1; mode=block',
  },
}
