export default {
  data: {
    total_count: 1,
    incomplete_results: false,
    items: [
      {
        name: 'package.json',
        path: 'ui/package.json',
        sha: 'fde77b13b7154e91fd8862680f84b499652c4586',
        url:
          'https://api.github.com/repositories/66407038/contents/ui/package.json?ref=1c583e8b7c6de4606313c5b79d1f4876070e1556',
        git_url:
          'https://api.github.com/repositories/66407038/git/blobs/fde77b13b7154e91fd8862680f84b499652c4586',
        html_url:
          'https://github.com/telusdigital/sample-repo/blob/1c583e8b7c6de4606313c5b79d1f4876070e1556/ui/package.json',
        repository: {
          id: 66407038,
          name: 'sample-repo',
          full_name: 'telusdigital/sample-repo',
          owner: {
            login: 'telusdigital',
            id: 9374493,
            avatar_url: 'https://avatars1.githubusercontent.com/u/9374493?v=4',
            gravatar_id: '',
            url: 'https://api.github.com/users/telusdigital',
            html_url: 'https://github.com/telusdigital',
            followers_url: 'https://api.github.com/users/telusdigital/followers',
            following_url: 'https://api.github.com/users/telusdigital/following{/other_user}',
            gists_url: 'https://api.github.com/users/telusdigital/gists{/gist_id}',
            starred_url: 'https://api.github.com/users/telusdigital/starred{/owner}{/repo}',
            subscriptions_url: 'https://api.github.com/users/telusdigital/subscriptions',
            organizations_url: 'https://api.github.com/users/telusdigital/orgs',
            repos_url: 'https://api.github.com/users/telusdigital/repos',
            events_url: 'https://api.github.com/users/telusdigital/events{/privacy}',
            received_events_url: 'https://api.github.com/users/telusdigital/received_events',
            type: 'Organization',
            site_admin: false,
          },
          private: false,
          html_url: 'https://github.com/telusdigital/sample-repo',
          description: 'TELUS Design System',
          fork: false,
          url: 'https://api.github.com/repos/telusdigital/sample-repo',
          forks_url: 'https://api.github.com/repos/telusdigital/sample-repo/forks',
          keys_url: 'https://api.github.com/repos/telusdigital/sample-repo/keys{/key_id}',
          collaborators_url:
            'https://api.github.com/repos/telusdigital/sample-repo/collaborators{/collaborator}',
          teams_url: 'https://api.github.com/repos/telusdigital/sample-repo/teams',
          hooks_url: 'https://api.github.com/repos/telusdigital/sample-repo/hooks',
          issue_events_url:
            'https://api.github.com/repos/telusdigital/sample-repo/issues/events{/number}',
          events_url: 'https://api.github.com/repos/telusdigital/sample-repo/events',
          assignees_url: 'https://api.github.com/repos/telusdigital/sample-repo/assignees{/user}',
          branches_url: 'https://api.github.com/repos/telusdigital/sample-repo/branches{/branch}',
          tags_url: 'https://api.github.com/repos/telusdigital/sample-repo/tags',
          blobs_url: 'https://api.github.com/repos/telusdigital/sample-repo/git/blobs{/sha}',
          git_tags_url: 'https://api.github.com/repos/telusdigital/sample-repo/git/tags{/sha}',
          git_refs_url: 'https://api.github.com/repos/telusdigital/sample-repo/git/refs{/sha}',
          trees_url: 'https://api.github.com/repos/telusdigital/sample-repo/git/trees{/sha}',
          statuses_url: 'https://api.github.com/repos/telusdigital/sample-repo/statuses/{sha}',
          languages_url: 'https://api.github.com/repos/telusdigital/sample-repo/languages',
          stargazers_url: 'https://api.github.com/repos/telusdigital/sample-repo/stargazers',
          contributors_url: 'https://api.github.com/repos/telusdigital/sample-repo/contributors',
          subscribers_url: 'https://api.github.com/repos/telusdigital/sample-repo/subscribers',
          subscription_url: 'https://api.github.com/repos/telusdigital/sample-repo/subscription',
          commits_url: 'https://api.github.com/repos/telusdigital/sample-repo/commits{/sha}',
          git_commits_url:
            'https://api.github.com/repos/telusdigital/sample-repo/git/commits{/sha}',
          comments_url: 'https://api.github.com/repos/telusdigital/sample-repo/comments{/number}',
          issue_comment_url:
            'https://api.github.com/repos/telusdigital/sample-repo/issues/comments{/number}',
          contents_url: 'https://api.github.com/repos/telusdigital/sample-repo/contents/{+path}',
          compare_url:
            'https://api.github.com/repos/telusdigital/sample-repo/compare/{base}...{head}',
          merges_url: 'https://api.github.com/repos/telusdigital/sample-repo/merges',
          archive_url:
            'https://api.github.com/repos/telusdigital/sample-repo/{archive_format}{/ref}',
          downloads_url: 'https://api.github.com/repos/telusdigital/sample-repo/downloads',
          issues_url: 'https://api.github.com/repos/telusdigital/sample-repo/issues{/number}',
          pulls_url: 'https://api.github.com/repos/telusdigital/sample-repo/pulls{/number}',
          milestones_url:
            'https://api.github.com/repos/telusdigital/sample-repo/milestones{/number}',
          notifications_url:
            'https://api.github.com/repos/telusdigital/sample-repo/notifications{?since,all,participating}',
          labels_url: 'https://api.github.com/repos/telusdigital/sample-repo/labels{/name}',
          releases_url: 'https://api.github.com/repos/telusdigital/sample-repo/releases{/id}',
          deployments_url: 'https://api.github.com/repos/telusdigital/sample-repo/deployments',
        },
        score: 5.1393394,
      },
    ],
  },
  headers: {
    'access-control-allow-origin': '*',
    'access-control-expose-headers':
      'ETag, Link, Retry-After, X-GitHub-OTP, X-RateLimit-Limit, X-RateLimit-Remaining, X-RateLimit-Reset, X-OAuth-Scopes, X-Accepted-OAuth-Scopes, X-Poll-Interval',
    'cache-control': 'no-cache',
    connection: 'close',
    'content-encoding': 'gzip',
    'content-security-policy': "default-src 'none'",
    'content-type': 'application/json; charset=utf-8',
    date: 'Wed, 28 Mar 2018 19:12:30 GMT',
    link:
      '<https://api.github.com/search/code?q=telusdigital%2Ftds+in%3Afile+user%3Atelusdigital+filename%3Apackage.json&page=2>; rel="next", <https://api.github.com/search/code?q=telusdigital%2Ftds+in%3Afile+user%3Atelusdigital+filename%3Apackage.json&page=5>; rel="last"',
    'referrer-policy': 'origin-when-cross-origin, strict-origin-when-cross-origin',
    server: 'GitHub.com',
    status: '200 OK',
    'strict-transport-security': 'max-age=31536000; includeSubdomains; preload',
    'transfer-encoding': 'chunked',
    'x-accepted-oauth-scopes': '',
    'x-content-type-options': 'nosniff',
    'x-frame-options': 'deny',
    'x-github-media-type': 'github.v3; format=json',
    'x-github-request-id': 'DA5B:13C8B:13DFB2D:269DBDA:5ABBE91D',
    'x-oauth-scopes': 'read:org, repo',
    'x-ratelimit-limit': '30',
    'x-ratelimit-remaining': '28',
    'x-ratelimit-reset': '1522264384',
    'x-runtime-rack': '0.232771',
    'x-xss-protection': '1; mode=block',
  },
}
